server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_database?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml